### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by ghost** [pawelniewie/docker-atlassian-stride#1]
ERROR: Service 'stride' failed to build: The command '/bin/sh -c apt-get --assume-yes update &&         apt-get --assume-yes install lsb-release wget apt-transport-https xterm &&      echo "deb https://packages.atlassian.com/debian/stride-apt-client $(lsb_release -c -s) main" > /etc/apt/sources.list.d/atlassian-stride.list &&  wget -O - https://packages.atlassian.com/api/gpg/key/public | apt-key add - &&   apt-get --assume-yes update &&  apt-get --assume-yes install stride libxss1 libgconf-2-4 libnss3 libasound2 &&  useradd -u $UID -m $USER' returned a non-zero code: 255

System - OpenSuse15

**Comment by pawelniewie** [comment]
Sorry to hear it doesn't work for you. I'm not using Stride anymore - we switched to Slack after Stride and HipChat were acquired by it.
